### ISSUE TITLE
String required error with newest version of sublime text

### ISSUE THREAD

**Issue by schreda** [Andersbakken/rtags#1281]
Hi.

I am always getting this error, it doesn't really matter what i am doing.
It seems that it can't show a popup, when something fails.

This is the error log:
```
RTags:ERROR: 2019-01-18 13:05:28,178 rtags.py::command_done [Thread-11]: Command task failed: RTags command failed with status 32.
exception calling callback for <Future at 0x2aaaae154610 state=finished returned tuple>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Installed Packages/RTagsComplete.sublime-package/rtags.py", line 151, in command_done
    location=location)
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/sublime.py", line 1140, in show_popup
    on_navigate, on_hide)
TypeError: String required
```

I also got another error before.. Maybe this has somoething to do with this issue?

```
error: RTags command failed with status 32.
RTags:DEBUG: 2019-01-18 13:03:42,391 rtags.py::command_done [Thread-11]: Command done callback hit <Future at 0x2aaaae0b64d0 state=finished returned tuple>
RTags:DEBUG: 2019-01-18 13:03:42,391 status.py::update_status [Thread-11]: Signalling status with error=<RTagsComplete.plugin.jobs.JobError object at 0x2aaaae1417d0>
RTags:DEBUG: 2019-01-18 13:03:42,391 status.py::clear_status [Thread-11]: Clearing status from view-id 15
RTags:ERROR: 2019-01-18 13:03:42,391 rtags.py::command_done [Thread-11]: Command task failed: RTags command failed with status 32.
RTags:DEBUG: 2019-01-18 13:03:42,391 settings.py::update_templates [Thread-11]: Templates update
RTags:DEBUG: 2019-01-18 13:03:42,391 settings.py::update_templates [Thread-11]: load_binary_resource of Packages/RTagsComplete.sublime-package/themes/Default/error_popup.html
exception calling callback for <Future at 0x2aaaae0b64d0 state=finished returned tuple>
Traceback (most recent call last):
  File "./python3.3/concurrent/futures/_base.py", line 296, in _invoke_callbacks
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Installed Packages/RTagsComplete.sublime-package/rtags.py", line 144, in command_done
    error.html_message())
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Installed Packages/RTagsComplete.sublime-package/plugin/settings.py", line 76, in template_as_html
    update_templates()
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/Data/Installed Packages/RTagsComplete.sublime-package/plugin/settings.py", line 61, in update_templates
    sublime.load_binary_resource(filepath).decode('utf-8')
  File "/nfs/lz/disks/home001/aschrede/sublime_text_3/sublime.py", line 199, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by tillt** [comment]
@schreda it appears you have a problem with a Sublime plugin based on rtags, but not with rtags itself. Please go ahead and file that problem at https://github.com/tillt/rtagscomplete/issues.
