### ISSUE TITLE
rp crashes when rtags is compiled with clang 3.5

### ISSUE THREAD

**Issue by cslux** [Andersbakken/rtags#454]
Hey @Andersbakken, 

as I was trying to see if I can reproduce the mentioned cmake issue in #389, without success, I just thought, why not install the clang compiled rtags binaries, and see how the indexing works. And see there, rp crashes very often. But doesn't happen when rtags is compiled with gcc since you have fixed it #403. 

**rdm output**
``` 
1/25 /bin/rp() [0x43f51a]
2/25 /lib64/libpthread.so.0(+0x10430) [0x7fd15e2bb430]
3/25 /bin/rp() [0x4516df]
4/25 ClangIndexer::addNamePermutations(CXCursor const&, Location const&, RTags::CursorType)
5/25 ClangIndexer::handleCursor(CXCursor const&, CXCursorKind, Location const&, Symbol**)
6/25 ClangIndexer::indexVisitor(CXCursor, CXCursor, void*)
7/25 /usr/lib64/llvm/libclang.so(+0x15650d) [0x7fd15effe50d]
8/25 /usr/lib64/llvm/libclang.so(+0x159911) [0x7fd15f001911]
9/25 /usr/lib64/llvm/libclang.so(+0x15b821) [0x7fd15f003821]
10/25 /usr/lib64/llvm/libclang.so(+0x155ff5) [0x7fd15effdff5]
11/25 /usr/lib64/llvm/libclang.so(+0x15653d) [0x7fd15effe53d]
12/25 /usr/lib64/llvm/libclang.so(+0x157ed1) [0x7fd15efffed1]
13/25 /usr/lib64/llvm/libclang.so(+0x155ff5) [0x7fd15effdff5]
14/25 /usr/lib64/llvm/libclang.so(+0x15653d) [0x7fd15effe53d]
15/25 /usr/lib64/llvm/libclang.so(+0x157ed1) [0x7fd15efffed1]
16/25 /usr/lib64/llvm/libclang.so(+0x155ff5) [0x7fd15effdff5]
17/25 /usr/lib64/llvm/libclang.so(+0x15653d) [0x7fd15effe53d]
18/25 /usr/lib64/llvm/libclang.so(+0x157ed1) [0x7fd15efffed1]
19/25 /usr/lib64/llvm/libclang.so(+0x1562ca) [0x7fd15effe2ca]
20/25 /usr/lib64/llvm/libclang.so(clang_visitChildren+0x14a) [0x7fd15f004f8a]
21/25 ClangIndexer::visit()
22/25 ClangIndexer::exec(String const&)
23/25 /bin/rp(main+0x4ee) [0x43f3ae]
24/25 /lib64/libc.so.6(__libc_start_main+0xf0) [0x7fd15cfe2700]
25/25 /bin/rp(_start+0x29) [0x43e539]

rp crashed, waiting for debugger pid: 13023
rp crashed, waiting for debugger pid: 13023
rp crashed, waiting for debugger pid: 12834
rp crashed, waiting for debugger pid: 12842
rp crashed, waiting for debugger pid: 12846
rp crashed, waiting for debugger pid: 13023
rp crashed, waiting for debugger pid: 13023
rp crashed, waiting for debugger pid: 13023
rp crashed, waiting for debugger pid: 12834
rp crashed, waiting for debugger pid: 12846
rp crashed, waiting for debugger pid: 13023
rp crashed, waiting for debugger pid: 12834
rp crashed, waiting for debugger pid: 12846
rp crashed, waiting for debugger pid: 13023
```

**rp backtrace**
```
#0  0x00007fd7cffe7a5d in nanosleep () from /lib64/libc.so.6
#1  0x00007fd7cffe78f4 in sleep () from /lib64/libc.so.6
#2  0x000000000043f5bb in sigHandler (signal=11) at /home/cschwarzgruber/Developing/third_party/rtags/src/rp.cpp:38
#3  <signal handler called>
#4  0x00000000004516df in tokenize (buf=0x7ffe40442640 "\030$\224\003", start=-805765122, templateStart=0x7ffe404424d4, templateEnd=0x7ffe404424d0,    sectionCount=0x7ffe404424cc, sections=0x7ffe404414c0) at /home/cschwarzgruber/Developing/third_party/rtags/src/ClangIndexer.cpp:327
#5  0x00000000004511ea in ClangIndexer::addNamePermutations (this=0x7ffe404c4b00, cursor=..., location=..., cursorType=RTags::Type_Cursor)    at /home/cschwarzgruber/Developing/third_party/rtags/src/ClangIndexer.cpp:516
#6  0x0000000000453422 in ClangIndexer::handleCursor (this=0x7ffe404c4b00, cursor=..., kind=CXCursor_UnexposedDecl, location=..., cursorPtr=0x0)    at /home/cschwarzgruber/Developing/third_party/rtags/src/ClangIndexer.cpp:1027
#7  0x0000000000452397 in ClangIndexer::indexVisitor (cursor=..., parent=..., data=0x7ffe404c4b00)     at /home/cschwarzgruber/Developing/third_party/rtags/src/ClangIndexer.cpp:650
#8  0x00007fd7d1f5b50d in clang::cxcursor::CursorVisitor::Visit(CXCursor, bool) () from /usr/lib64/llvm/libclang.so
#9  0x00007fd7d1f61a1c in clang::cxcursor::CursorVisitor::RunVisitorWorkList(llvm::SmallVector<clang::cxcursor::VisitorJob, 10u>&) ()   from /usr/lib64/llvm/libclang.so
#10 0x00007fd7d1f5acfb in clang::cxcursor::CursorVisitor::Visit(clang::Stmt const*) () from /usr/lib64/llvm/libclang.so
#11 0x00007fd7d1f5af21 in clang::cxcursor::CursorVisitor::VisitChildren(CXCursor) () from /usr/lib64/llvm/libclang.so
#12 0x00007fd7d1f5b53d in clang::cxcursor::CursorVisitor::Visit(CXCursor, bool) () from /usr/lib64/llvm/libclang.so
#13 0x00007fd7d1f60961 in clang::cxcursor::CursorVisitor::VisitFunctionDecl(clang::FunctionDecl*) () from /usr/lib64/llvm/libclang.so
#14 0x00007fd7d1f5aff5 in clang::cxcursor::CursorVisitor::VisitChildren(CXCursor) () from /usr/lib64/llvm/libclang.so
#15 0x00007fd7d1f5b53d in clang::cxcursor::CursorVisitor::Visit(CXCursor, bool) () from /usr/lib64/llvm/libclang.so
#16 0x00007fd7d1f5ced1 in clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*) () from /usr/lib64/llvm/libclang.so
#17 0x00007fd7d1f5aff5 in clang::cxcursor::CursorVisitor::VisitChildren(CXCursor) () from /usr/lib64/llvm/libclang.so
#18 0x00007fd7d1f5b53d in clang::cxcursor::CursorVisitor::Visit(CXCursor, bool) () from /usr/lib64/llvm/libclang.so
#19 0x00007fd7d1f5ced1 in clang::cxcursor::CursorVisitor::VisitDeclContext(clang::DeclContext*) () from /usr/lib64/llvm/libclang.so
#20 0x00007fd7d1f5b2ca in clang::cxcursor::CursorVisitor::VisitChildren(CXCursor) () from /usr/lib64/llvm/libclang.so
#21 0x00007fd7d1f61f8a in clang_visitChildren () from /usr/lib64/llvm/libclang.so
#22 0x000000000044c2ee in ClangIndexer::visit (this=0x7ffe404c4b00) at /home/cschwarzgruber/Developing/third_party/rtags/src/ClangIndexer.cpp:1526
#23 0x000000000044aa2c in ClangIndexer::exec (this=0x7ffe404c4b00, data=...) at /home/cschwarzgruber/Developing/third_party/rtags/src/ClangIndexer.cpp:167
#24 0x000000000043f3ae in main (argc=1, argv=0x7ffe404c4fb8) at /home/cschwarzgruber/Developing/third_party/rtags/src/rp.cpp:116

```

------------------------------ `rdm --job-count 1`
I have added an error print macro to print the value of idx. But that shows completely different values than gdb!? :-/

``` diff
1 file changed, 1 insertion(+)
src/ClangIndexer.cpp | 1 +

modified   src/ClangIndexer.cpp
@@ -324,6 +324,7 @@ static inline void tokenize(const char *buf, int start,
 
     int idx = start;
     while (true) {
+	error("idx size = %d", idx);
         switch (buf[++idx]) {
         case '<':
             if (buf[idx + 1] == '<') {

```
``` 
idx size = 524286

Caught signal 11
1/18 /bin/rp() [0x43f51a]
2/18 /lib64/libpthread.so.0(+0x10430) [0x7f798e5f4430]
3/18 /bin/rp() [0x451745]
4/18 ClangIndexer::addNamePermutations(CXCursor const&, Location const&, RTags::CursorType)
5/18 ClangIndexer::handleCursor(CXCursor const&, CXCursorKind, Location const&, Symbol**)
6/18 ClangIndexer::indexVisitor(CXCursor, CXCursor, void*)
7/18 /usr/lib64/llvm/libclang.so(+0x15650d) [0x7f798f33750d]
8/18 /usr/lib64/llvm/libclang.so(+0x157ed1) [0x7f798f338ed1]
9/18 /usr/lib64/llvm/libclang.so(+0x155ff5) [0x7f798f336ff5]
10/18 /usr/lib64/llvm/libclang.so(+0x15653d) [0x7f798f33753d]
11/18 /usr/lib64/llvm/libclang.so(+0x157ed1) [0x7f798f338ed1]
12/18 /usr/lib64/llvm/libclang.so(+0x1562ca) [0x7f798f3372ca]
13/18 /usr/lib64/llvm/libclang.so(clang_visitChildren+0x14a) [0x7f798f33df8a]
14/18 ClangIndexer::visit()
15/18 ClangIndexer::exec(String const&)
16/18 /bin/rp(main+0x4ee) [0x43f3ae]
17/18 /lib64/libc.so.6(__libc_start_main+0xf0) [0x7f798d31b700]
18/18 /bin/rp(_start+0x29) [0x43e539]
```
In gdb
```
(gdb) p start
$1 = 1654128893
(gdb) p idx
$2 = 1654128894
```
I definitely do not understand this right now.

**Comment by anders** [comment]
wrong @anders

**Comment by cslux** [comment]
Ups, @anders, sry
