### ISSUE TITLE
rdm crashes because of a std::out_of_range

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [Andersbakken/rtags#875]
Hi,

rdm crashes often with my heavily-templated c++14 project. (code is [here](https://github.com/DavidPfander-UniStuttgart/MatrixMultiplicationHPX))

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
Caught signal 6
./bin/rdm[0x4564df]
```

Any ideas? What information can I provide to you that my be relevant?

**Comment by DavidPfander-UniStuttgart** [comment]
Added gdb stacktrace, in Project.cpp:2479 the error is triggered.

```
Restoring /home/pfandedd/git/MatrixMultiplicationHPX/ ..........................................
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)

Thread 1 "rdm" received signal SIGABRT, Aborted.
0x00007ffff5b5e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff5b5e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff5b6002a in __GI_abort () at abort.c:89
#2  0x00007ffff6ae25cd in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6ae0376 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6ae03c1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6ae05d9 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6b0a037 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00000000008ea3e7 in std::vector<Source, std::allocator<Source> >::_M_range_check (this=0x1954c80, __n=1) at /usr/include/c++/6/bits/stl_vector.h:804
#8  0x00000000008e3e7a in std::vector<Source, std::allocator<Source> >::at (this=0x1954c80, __n=1) at /usr/include/c++/6/bits/stl_vector.h:825
#9  0x0000000000994af0 in Project::<lambda(SourceList&)>::operator()(SourceList &) const (__closure=0x7fffffffae10, list=...) at /home/pfandedd/rtags/src/Project.cpp:2479
#10 0x000000000099f311 in std::_Function_handler<Project::VisitResult(SourceList&), Project::processParseData(IndexParseData&&)::<lambda(SourceList&)> >::_M_invoke(const std::_Any_data &, SourceList &) (
    __functor=..., __args#0=...) at /usr/include/c++/6/functional:1726
#11 0x00000000009b3778 in std::function<Project::VisitResult (SourceList&)>::operator()(SourceList&) const (this=0x7fffffffae10, __args#0=...) at /usr/include/c++/6/functional:2136
#12 0x0000000000995545 in Project::forEachSourceList(Hash<unsigned int, SourceList>&, std::function<Project::VisitResult (SourceList&)>) (sources=..., cb=...) at /home/pfandedd/rtags/src/Project.cpp:2541
#13 0x0000000000994ea3 in Project::processParseData(IndexParseData&&) (this=0x18fbab0, data=<unknown type in /home/pfandedd/rtags/bin/rdm, CU 0x14a7d69, DIE 0x15a18cc>)
    at /home/pfandedd/rtags/src/Project.cpp:2494
#14 0x00000000009938e6 in Project::reloadCompileCommands (this=0x18fbab0) at /home/pfandedd/rtags/src/Project.cpp:2334
#15 0x0000000000983ace in Project::init (this=0x18fbab0) at /home/pfandedd/rtags/src/Project.cpp:444
#16 0x000000000078e3ab in Server::addProject (this=0xd51310, path=...) at /home/pfandedd/rtags/src/Server.cpp:328
#17 0x000000000079d424 in Server::load (this=0xd51310) at /home/pfandedd/rtags/src/Server.cpp:1954
#18 0x000000000078d0fe in Server::init (this=0xd51310, options=...) at /home/pfandedd/rtags/src/Server.cpp:193
#19 0x00000000007357f0 in main (argc=1, argv=0x7fffffffdd88) at /home/pfandedd/rtags/src/rdm.cpp:821
```

**Comment by Andersbakken** [comment]
I think I know what's going on. Can you try with the latest patch?

Anders

**Comment by DavidPfander-UniStuttgart** [comment]
With git pull, cmake, make and a reindex of the project, rdm run. I can't really say whether it's stable so far, because I would like to you rtags for at least some hours without a crash. If I type an error, it is at least displayed correctly in the rdm log.

Unfortunately, since yesterday flycheck with rtags doesn't seem to work any more. I get a 
```
Error while checking syntax automatically: (wrong-type-argument stringp nil)
```
in the Messages buffer. This only happens with rtags, with pure flycheck and clang this error doesn't occur.

Some versions:
Flycheck 20161216.1227
rtags              20161216.1019

GNU Emacs 24.5.1

**Comment by Andersbakken** [comment]
I suspect this might be a mismatch between your rtags.el/flycheck-rtags.el
and your build of rtags. Can you try to load the el files from your build
instead of from melpa?

regards

Anders

**Comment by DavidPfander-UniStuttgart** [comment]
I originally installed rtags from melpa. My problem goes away version from git. 

I'll close this issue now, because rdm seems to be stable.

Thank you very much for this great projects, Anders!
